from setuptools import setup

setup(
    name='FlaskApp',
    version='0.8',
    packages=['', 'venv.Lib.site-packages.odo', 'venv.Lib.site-packages.odo.tests',
              'venv.Lib.site-packages.odo.backends', 'venv.Lib.site-packages.odo.backends.tests',
              'venv.Lib.site-packages.tlz', 'venv.Lib.site-packages.amqp', 'venv.Lib.site-packages.pika',
              'venv.Lib.site-packages.pika.adapters', 'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.vine',
              'venv.Lib.site-packages.click', 'venv.Lib.site-packages.flask', 'venv.Lib.site-packages.flask.json',
              'venv.Lib.site-packages.kombu', 'venv.Lib.site-packages.kombu.utils',
              'venv.Lib.site-packages.kombu.transport', 'venv.Lib.site-packages.kombu.transport.virtual',
              'venv.Lib.site-packages.kombu.transport.sqlalchemy', 'venv.Lib.site-packages.kombu.asynchronous',
              'venv.Lib.site-packages.kombu.asynchronous.aws', 'venv.Lib.site-packages.kombu.asynchronous.aws.sqs',
              'venv.Lib.site-packages.kombu.asynchronous.http', 'venv.Lib.site-packages.numpy',
              'venv.Lib.site-packages.numpy.ma', 'venv.Lib.site-packages.numpy.ma.tests',
              'venv.Lib.site-packages.numpy.doc', 'venv.Lib.site-packages.numpy.fft',
              'venv.Lib.site-packages.numpy.fft.tests', 'venv.Lib.site-packages.numpy.lib',
              'venv.Lib.site-packages.numpy.lib.tests', 'venv.Lib.site-packages.numpy.core',
              'venv.Lib.site-packages.numpy.core.tests', 'venv.Lib.site-packages.numpy.f2py',
              'venv.Lib.site-packages.numpy.f2py.tests', 'venv.Lib.site-packages.numpy.tests',
              'venv.Lib.site-packages.numpy.compat', 'venv.Lib.site-packages.numpy.linalg',
              'venv.Lib.site-packages.numpy.linalg.tests', 'venv.Lib.site-packages.numpy.random',
              'venv.Lib.site-packages.numpy.random.tests', 'venv.Lib.site-packages.numpy.testing',
              'venv.Lib.site-packages.numpy.testing.tests', 'venv.Lib.site-packages.numpy.testing.nose_tools',
              'venv.Lib.site-packages.numpy.distutils', 'venv.Lib.site-packages.numpy.distutils.tests',
              'venv.Lib.site-packages.numpy.distutils.command', 'venv.Lib.site-packages.numpy.distutils.fcompiler',
              'venv.Lib.site-packages.numpy.matrixlib', 'venv.Lib.site-packages.numpy.matrixlib.tests',
              'venv.Lib.site-packages.numpy.polynomial', 'venv.Lib.site-packages.numpy.polynomial.tests',
              'venv.Lib.site-packages.toolz', 'venv.Lib.site-packages.toolz.curried',
              'venv.Lib.site-packages.toolz.sandbox', 'venv.Lib.site-packages.celery',
              'venv.Lib.site-packages.celery.app', 'venv.Lib.site-packages.celery.bin',
              'venv.Lib.site-packages.celery.apps', 'venv.Lib.site-packages.celery.task',
              'venv.Lib.site-packages.celery.utils', 'venv.Lib.site-packages.celery.utils.static',
              'venv.Lib.site-packages.celery.utils.dispatch', 'venv.Lib.site-packages.celery.events',
              'venv.Lib.site-packages.celery.fixups', 'venv.Lib.site-packages.celery.worker',
              'venv.Lib.site-packages.celery.worker.consumer', 'venv.Lib.site-packages.celery.contrib',
              'venv.Lib.site-packages.celery.contrib.testing', 'venv.Lib.site-packages.celery.loaders',
              'venv.Lib.site-packages.celery.backends', 'venv.Lib.site-packages.celery.backends.database',
              'venv.Lib.site-packages.celery.security', 'venv.Lib.site-packages.celery.concurrency',
              'venv.Lib.site-packages.jinja2', 'venv.Lib.site-packages.pandas', 'venv.Lib.site-packages.pandas.io',
              'venv.Lib.site-packages.pandas.io.sas', 'venv.Lib.site-packages.pandas.io.json',
              'venv.Lib.site-packages.pandas.io.formats', 'venv.Lib.site-packages.pandas.io.msgpack',
              'venv.Lib.site-packages.pandas.io.clipboard', 'venv.Lib.site-packages.pandas.api',
              'venv.Lib.site-packages.pandas.api.types', 'venv.Lib.site-packages.pandas.api.extensions',
              'venv.Lib.site-packages.pandas.core', 'venv.Lib.site-packages.pandas.core.util',
              'venv.Lib.site-packages.pandas.core.tools', 'venv.Lib.site-packages.pandas.core.arrays',
              'venv.Lib.site-packages.pandas.core.dtypes', 'venv.Lib.site-packages.pandas.core.sparse',
              'venv.Lib.site-packages.pandas.core.groupby', 'venv.Lib.site-packages.pandas.core.indexes',
              'venv.Lib.site-packages.pandas.core.reshape', 'venv.Lib.site-packages.pandas.core.computation',
              'venv.Lib.site-packages.pandas.util', 'venv.Lib.site-packages.pandas._libs',
              'venv.Lib.site-packages.pandas._libs.tslibs', 'venv.Lib.site-packages.pandas.tests',
              'venv.Lib.site-packages.pandas.tests.io', 'venv.Lib.site-packages.pandas.tests.io.sas',
              'venv.Lib.site-packages.pandas.tests.io.json', 'venv.Lib.site-packages.pandas.tests.io.parser',
              'venv.Lib.site-packages.pandas.tests.io.formats', 'venv.Lib.site-packages.pandas.tests.io.msgpack',
              'venv.Lib.site-packages.pandas.tests.api', 'venv.Lib.site-packages.pandas.tests.util',
              'venv.Lib.site-packages.pandas.tests.frame', 'venv.Lib.site-packages.pandas.tests.tools',
              'venv.Lib.site-packages.pandas.tests.dtypes', 'venv.Lib.site-packages.pandas.tests.scalar',
              'venv.Lib.site-packages.pandas.tests.scalar.period',
              'venv.Lib.site-packages.pandas.tests.scalar.interval',
              'venv.Lib.site-packages.pandas.tests.scalar.timedelta',
              'venv.Lib.site-packages.pandas.tests.scalar.timestamp', 'venv.Lib.site-packages.pandas.tests.series',
              'venv.Lib.site-packages.pandas.tests.series.indexing', 'venv.Lib.site-packages.pandas.tests.sparse',
              'venv.Lib.site-packages.pandas.tests.sparse.frame', 'venv.Lib.site-packages.pandas.tests.sparse.series',
              'venv.Lib.site-packages.pandas.tests.tslibs', 'venv.Lib.site-packages.pandas.tests.generic',
              'venv.Lib.site-packages.pandas.tests.groupby', 'venv.Lib.site-packages.pandas.tests.groupby.aggregate',
              'venv.Lib.site-packages.pandas.tests.indexes', 'venv.Lib.site-packages.pandas.tests.indexes.period',
              'venv.Lib.site-packages.pandas.tests.indexes.interval',
              'venv.Lib.site-packages.pandas.tests.indexes.datetimes',
              'venv.Lib.site-packages.pandas.tests.indexes.timedeltas', 'venv.Lib.site-packages.pandas.tests.reshape',
              'venv.Lib.site-packages.pandas.tests.reshape.merge', 'venv.Lib.site-packages.pandas.tests.tseries',
              'venv.Lib.site-packages.pandas.tests.tseries.offsets', 'venv.Lib.site-packages.pandas.tests.indexing',
              'venv.Lib.site-packages.pandas.tests.indexing.interval', 'venv.Lib.site-packages.pandas.tests.plotting',
              'venv.Lib.site-packages.pandas.tests.extension', 'venv.Lib.site-packages.pandas.tests.extension.base',
              'venv.Lib.site-packages.pandas.tests.extension.json',
              'venv.Lib.site-packages.pandas.tests.extension.decimal',
              'venv.Lib.site-packages.pandas.tests.extension.category', 'venv.Lib.site-packages.pandas.tests.internals',
              'venv.Lib.site-packages.pandas.tests.categorical', 'venv.Lib.site-packages.pandas.tests.computation',
              'venv.Lib.site-packages.pandas.tools', 'venv.Lib.site-packages.pandas.types',
              'venv.Lib.site-packages.pandas.compat', 'venv.Lib.site-packages.pandas.compat.numpy',
              'venv.Lib.site-packages.pandas.errors', 'venv.Lib.site-packages.pandas.formats',
              'venv.Lib.site-packages.pandas.tseries', 'venv.Lib.site-packages.pandas.plotting',
              'venv.Lib.site-packages.pandas.computation', 'venv.Lib.site-packages.blinker',
              'venv.Lib.site-packages.jsonify', 'venv.Lib.site-packages.MySQLdb',
              'venv.Lib.site-packages.MySQLdb.constants', 'venv.Lib.site-packages.pymysql',
              'venv.Lib.site-packages.pymysql.tests', 'venv.Lib.site-packages.pymysql.tests.thirdparty',
              'venv.Lib.site-packages.pymysql.tests.thirdparty.test_MySQLdb',
              'venv.Lib.site-packages.pymysql.constants', 'venv.Lib.site-packages.billiard',
              'venv.Lib.site-packages.billiard.dummy', 'venv.Lib.site-packages.dateutil',
              'venv.Lib.site-packages.dateutil.tz', 'venv.Lib.site-packages.dateutil.parser',
              'venv.Lib.site-packages.dateutil.zoneinfo', 'venv.Lib.site-packages.eventlet',
              'venv.Lib.site-packages.eventlet.hubs', 'venv.Lib.site-packages.eventlet.green',
              'venv.Lib.site-packages.eventlet.green.http', 'venv.Lib.site-packages.eventlet.green.urllib',
              'venv.Lib.site-packages.eventlet.green.OpenSSL', 'venv.Lib.site-packages.eventlet.zipkin',
              'venv.Lib.site-packages.eventlet.zipkin._thrift',
              'venv.Lib.site-packages.eventlet.zipkin._thrift.zipkinCore', 'venv.Lib.site-packages.eventlet.greenio',
              'venv.Lib.site-packages.eventlet.support', 'venv.Lib.site-packages.eventlet.support.dns',
              'venv.Lib.site-packages.eventlet.support.dns.rdtypes',
              'venv.Lib.site-packages.eventlet.support.dns.rdtypes.IN',
              'venv.Lib.site-packages.eventlet.support.dns.rdtypes.ANY', 'venv.Lib.site-packages.networkx',
              'venv.Lib.site-packages.networkx.tests', 'venv.Lib.site-packages.networkx.utils',
              'venv.Lib.site-packages.networkx.linalg', 'venv.Lib.site-packages.networkx.classes',
              'venv.Lib.site-packages.networkx.drawing', 'venv.Lib.site-packages.networkx.testing',
              'venv.Lib.site-packages.networkx.readwrite', 'venv.Lib.site-packages.networkx.readwrite.json_graph',
              'venv.Lib.site-packages.networkx.algorithms', 'venv.Lib.site-packages.networkx.algorithms.flow',
              'venv.Lib.site-packages.networkx.algorithms.tree', 'venv.Lib.site-packages.networkx.algorithms.coloring',
              'venv.Lib.site-packages.networkx.algorithms.bipartite',
              'venv.Lib.site-packages.networkx.algorithms.community',
              'venv.Lib.site-packages.networkx.algorithms.operators',
              'venv.Lib.site-packages.networkx.algorithms.traversal',
              'venv.Lib.site-packages.networkx.algorithms.centrality',
              'venv.Lib.site-packages.networkx.algorithms.components',
              'venv.Lib.site-packages.networkx.algorithms.isomorphism',
              'venv.Lib.site-packages.networkx.algorithms.connectivity',
              'venv.Lib.site-packages.networkx.algorithms.approximation',
              'venv.Lib.site-packages.networkx.algorithms.assortativity',
              'venv.Lib.site-packages.networkx.algorithms.link_analysis',
              'venv.Lib.site-packages.networkx.algorithms.shortest_paths', 'venv.Lib.site-packages.networkx.generators',
              'venv.Lib.site-packages.werkzeug', 'venv.Lib.site-packages.werkzeug.debug',
              'venv.Lib.site-packages.werkzeug.contrib', 'venv.Lib.site-packages.datashape',
              'venv.Lib.site-packages.datashape.util', 'venv.Lib.site-packages.datashape.tests',
              'venv.Lib.site-packages.markupsafe', 'venv.Lib.site-packages.sqlalchemy',
              'venv.Lib.site-packages.sqlalchemy.ext', 'venv.Lib.site-packages.sqlalchemy.ext.declarative',
              'venv.Lib.site-packages.sqlalchemy.orm', 'venv.Lib.site-packages.sqlalchemy.sql',
              'venv.Lib.site-packages.sqlalchemy.util', 'venv.Lib.site-packages.sqlalchemy.event',
              'venv.Lib.site-packages.sqlalchemy.engine', 'venv.Lib.site-packages.sqlalchemy.testing',
              'venv.Lib.site-packages.sqlalchemy.testing.suite', 'venv.Lib.site-packages.sqlalchemy.testing.plugin',
              'venv.Lib.site-packages.sqlalchemy.dialects', 'venv.Lib.site-packages.sqlalchemy.dialects.mssql',
              'venv.Lib.site-packages.sqlalchemy.dialects.mysql', 'venv.Lib.site-packages.sqlalchemy.dialects.oracle',
              'venv.Lib.site-packages.sqlalchemy.dialects.sqlite', 'venv.Lib.site-packages.sqlalchemy.dialects.sybase',
              'venv.Lib.site-packages.sqlalchemy.dialects.firebird',
              'venv.Lib.site-packages.sqlalchemy.dialects.postgresql', 'venv.Lib.site-packages.sqlalchemy.databases',
              'venv.Lib.site-packages.sqlalchemy.connectors', 'venv.Lib.site-packages.flask_sqlalchemy',
              'venv.Lib.site-packages.multipledispatch', 'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.operations'],
    url='',
    license='',
    author='sourabh',
    author_email='psourabh92@gmail.com',
    description='Data Science Deployed'
)
